[project]
name = "complex-project"
version = "0.1.0"
description = "Complex Project"
authors = []
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch (==2.7.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
